Aatu/FieryVoid

source/server/model/ships/orieni/vengeful.php
Hey guys check out this simple addition and let me know if it works.
=> Addition of Vengeful Frigate

source/server/model/ships/centauri_old/centaurum.php, source/server/model/ships/centauri_old/equata.php, source/server/model/ships/centauri_old/falassa.php, source/server/model/ships/centauri_old/falenna.php, source/server/model/ships/centauri_old/optine.php, source/server/model/ships/centauri_old/valtor.php, source/server/model/ships/drazi_old/dragon.php
Finished the latest batch, please give them a once over.
=> Scs updates2

source/public/client/power.js, source/server/model/ships/brakiri/brokados.php, source/server/model/systems/baseSystems.php
=> Turns out Shield generator fix was very simple based on rules check.

source/server/model/ships/centauri_old/kendari.php
Cram this into the next update please
=> Closes #127

source/server/model/ships/EA/artemisEscort.php, source/server/model/ships/EA/godAlpha.php, source/server/model/ships/EA/tethys.php, source/server/model/ships/ShipClasses.php, source/server/model/ships/drazi/kestrel.php, source/server/model/ships/drazi/nightfalcon.php, source/server/model/ships/drazi/sunhawk.php
=> Added the requested hit charts

source/autoload.php, source/server/model/ships/civilians/cargoTug.php, source/server/model/ships/civilians/civilianFreighter.php, source/server/model/ships/civilians/civilianTanker.php, source/server/model/ships/civilians/fastFreighter.php, source/server/model/ships/civilians/liner.php, source/server/model/ships/civilians/ore.php, source/server/model/ships/civilians/pirateHunter.php, source/server/model/ships/civilians/qship.php, source/server/model/ships/civilians/tankerTug.php
Closes #125 
These should be done, one ship is without hit chart, I built it before figuring out that the hit chart wouldn't work with it yet.  It can run with the old rules for the time being.  
Let me know if I need to make any changes.
=> Added Civilian Ships

source/server/model/ships/yolu/aluin.php, source/server/model/ships/yolu/hastan.php, source/server/model/ships/yolu/maishan.php, source/server/model/ships/yolu/maitau.php, source/server/model/ships/yolu/malau.php, source/server/model/ships/yolu/maltra.php, source/server/model/ships/yolu/nashana.php, source/server/model/ships/yolu/notai.php, source/server/model/ships/yolu/notali.php, source/server/model/ships/yolu/udran.php, source/server/model/ships/yolu/ulana.php, source/server/model/ships/yolu/yuan.php
Closes #142 
Let me know if I need to make any changes. No image changes need to be made, just edited existing ships.
=> Added Hit Charts and fixed any discrepencies from SCS

source/server/model/ships/EA/delphi.php, source/server/model/ships/EA/oracleScout.php, source/server/model/ships/brakiri/calorta.php, source/server/model/ships/brakiri/halos.php, source/server/model/ships/brakiri/torsha.php, source/server/model/ships/narn/vakar.php, source/server/model/ships/yolu/maltra.php
Scouts did not have proper entry in hit chart for their ELINT Scanners.
=> Scanner Hit Chart Fix

source/server/model/ships/minbari/ashinta.php, source/server/model/ships/minbari/esharan.php, source/server/model/ships/minbari/greySharlin.php, source/server/model/ships/minbari/leshath.php, source/server/model/ships/minbari/letann.php, source/server/model/ships/minbari/morshin.php, source/server/model/ships/minbari/neshatan.php, source/server/model/ships/minbari/retlata.php, source/server/model/ships/minbari/rolentha.php, source/server/model/ships/minbari/shantavi.php, source/server/model/ships/minbari/sharaal.php, source/server/model/ships/minbari/sharlin.php, source/server/model/ships/minbari/shaveenPatrolCutter.php, source/server/model/ships/minbari/shaveenPoliceLeader.php, source/server/model/ships/minbari/sheganna.php, source/server/model/ships/minbari/tigara.php, source/server/model/ships/minbari/tigarin.php, source/server/model/ships/minbari/tinashi.php, source/server/model/ships/minbari/torotha.php, source/server/model/ships/minbari/tradana.php, source/server/model/ships/minbari/trolata.php
=> Updated Hitcharts

source/public/games.php
Updated and Activated News in Lobby
=> News in Lobby

source/public/client/games.js
In 'Active fire' section only one game was shown. This correction should allow display of multiple games.
=> multiple games in 'active fire' section

source/autoload.php, source/server/model/ships/centauri/phalanx.php, source/server/model/ships/customs/wlcChlonasLerTarFlight.php, source/server/model/ships/customs/wlcChlonasSaTrevanFlight.php, source/server/model/ships/customs/wlcChlonasVesTek.php, source/server/model/ships/orieni/staunch.php, source/server/model/ships/orieni/steadfast.php, source/server/model/ships/orieni/steadfast1780.php, source/server/model/ships/orieni/stormfront.php, source/server/model/ships/orieni/stormfront1874.php, source/server/model/ships/orieni/vengeful.php, source/server/model/ships/orieni/vengeful1780.php, source/server/model/ships/orieni/vigilant.php, source/server/model/ships/orieni/virtue.php, source/server/model/ships/orieni/virtue1783.php
new ships and corrections to old ones
=> Marcin sawicki scs fixes 3

source/public/client/weaponManager.js, source/server/model/ships/ShipClasses.php
This should correct profile choice in front end and section choice at server end (while firing at range 0).
=> Marcin sawicki get hit section bugfix

source/server/model/ships/ShipClasses.php
I won't delete this branch for now so you can see the code changes easily.  I'm going to merge it though since I've completed some testing on it.
=> Hit chart bypass fix

source/public/client/weaponManager.js, source/server/model/ships/minbari/whitestar.php
Tom, this one is left not loaded into master. Which is strange, as I thought that I made an error that causes MCV PRIMARY systems to be targetable... well, apparently not . But this will hopefully solve the error anyway ;)
=> Marcin sawicki called shots

source/public/client/weaponManager.js
This fix shall allow me to target bases :) . I guess in Your case browses behaves differently after error...
=> fix to targeting bases

source/server/model/ships/centauri_old/centaurum.php, source/server/model/ships/narn/varnic.php
=> Marcin sawicki test

source/public/client/UI/shipwindow.js
TD and TC display on ship info window: shwitched descriptions so they'll be correct.
=> TD and TC switch

source/server/model/ships/ShipClasses.php
StarBaseSixSections should have appropriate getPiercingLocations method. Adding one.
Hopefully this will cause Piercing fire to behave properly.
=> complete StarBaseSixSections

source/public/client/power.js
deeper attempt at bypassing Jammer :)
=> Marcin sawicki last turn jammer

source/public/chpass.php, source/server/controller/DBManager.php, source/server/controller/Manager.php
functionality to change password
=> Marcin sawicki change passwd

source/server/model/weapons/AoE.php, source/server/model/weapons/ammo.php, source/server/model/weapons/customs.php, source/server/model/weapons/defensive.php, source/server/model/weapons/gravitic.php, source/server/model/weapons/ion.php, source/server/model/weapons/lasers.php, source/server/model/weapons/matter.php, source/server/model/weapons/missile.php, source/server/model/weapons/molecular.php, source/server/model/weapons/particle.php, source/server/model/weapons/plasma.php, source/server/model/weapons/pulse.php, source/server/model/weapons/specialWeapons.php, source/server/model/weapons/torpedo.php
quick fix to firing order - mostly without major changes
=> Marcin sawicki firing order

source/public/client/UI/shipclickable.js, source/public/games.php, source/public/reg.php, source/server/model/ships/raiders/skiff.php
front page changed, also a few other changes...
=> Marcin sawicki front page

source/server/model/ships/ShipClasses.php, source/server/model/weapons/weapon.php
Flash mode updated - new way of preparing hit table
=> Marcin sawicki flash

source/server/controller/DBManager.php, source/server/model/ships/FighterFlight.php, source/server/model/ships/ShipClasses.php, source/server/model/weapons/AoE.php, source/server/model/weapons/lasers.php, source/server/model/weapons/linkedWeapon.php, source/server/model/weapons/molecular.php, source/server/model/weapons/weapon.php
firing refit - finishing touches (...and there'll be syntax fixes too, of course...)
=> Marcin sawicki firing refit part2

source/autoload.php, source/server/model/ships/deneth/wardOSAT.php, source/server/model/ships/starwars_centauri/zzftrYWing.php, source/server/model/weapons/customSW.php, source/server/model/weapons/weapon.php
neq quality to changing firing modes ;)
=> Mjs weapon technology change

source/autoload.php, source/server/model/ships/markab/drofta.php, source/server/model/ships/markab/droftaE.php, source/server/model/ships/markab/droftaN.php, source/server/model/ships/markab/kowart.php, source/server/model/ships/markab/mafka.php, source/server/model/ships/markab/maftora.php, source/server/model/ships/markab/makar.php, source/server/model/ships/markab/malaka.php, source/server/model/ships/markab/mantaka.php, source/server/model/ships/markab/markabliner.php, source/server/model/ships/markab/martoba.php, source/server/model/ships/markab/romak.php, source/server/model/ships/markab/shadrak.php, source/server/model/ships/markab/shafab.php, source/server/model/ships/markab/shofab.php, source/server/model/ships/markab/talafat.php
Hey,
I've finished the main body of Markab units, but I don't have my own test rig any more.  Can you check these out?
Right now they are using Human ship images, I'll have to come up with something else for them.  
Also, I need another weapon for the fighters, They are using the light scattergun, 2d6 at 1d3 shots.  I was thinking we could just give them two shots, a pretty good fighter weapon, but swingy.
=> Main addition of Markab Units

source/autoload.php, source/server/model/ships/civilians/bulkFreighter.php, source/server/model/ships/civilians/bulkOreFreighter.php, source/server/model/ships/civilians/jumpgate.php, source/server/model/ships/civilians/missileBarge.php, source/server/model/ships/civilians/oreBarge.php, source/server/model/ships/civilians/passengerLiner.php, source/server/model/ships/civilians/skylark.php, source/server/model/ships/llort/freeTrader.php, source/server/model/ships/llort/freeTraderPulsar.php
This should be ready for merge as well
=> Add new Civilian and Llort ships, as well as update hit chart for Ore Barge

source/server/model/ships/brakiri/bashnar.php, source/server/model/ships/brakiri/brathon.php, source/server/model/ships/brakiri/brathonCannon.php, source/server/model/ships/brakiri/lykorai.php, source/server/model/ships/narn/tgan.php, source/server/model/ships/orieni/benevolent.php
=> Hit chart updates

source/public/client/weaponManager.js, source/server/model/systems/baseSystems.php
=> Mjs firingfix

source/public/client/renderer/sprite/webglSprite.js
- Load textures with ImageBitmapLoader and cache them
- Cache geometries
- Clone material to only have one copy of shaders
=> Possible sprite optimizations

source/public/client/UI/ShipTooltip.js, source/public/client/UI/reactJs/system/SystemInfoButtons.js, source/public/client/declarations.js, source/public/client/gamedata.js, source/public/client/movement.js, source/public/client/renderer/animationStrategy/ReplayAnimationStrategy.js, source/public/client/ships.js, source/public/games.php, source/public/styles/base.css, source/server/Phase/DeploymentGamePhase.php, source/server/controller/DBManager.php, source/server/model/ships/dilgar/garasoch.php, source/server/model/ships/dilgar/thorun.php, source/server/model/ships/dilgar/thorunEarly.php, source/server/model/ships/dilgar/thorunHeavy.php, source/server/model/ships/dilgar/thorunHeavyNav.php, source/server/model/weapons/weapon.php
A bunch of fixes (Dilgar fighters, Game Lobby details, new Declarations screen, some more movement...).
Also, mass mode change I always wanted to have!
=> Marcin fixes2

source/public/chat.php, source/public/client/gamedata.js
=> Marcin fixes4

source/public/client/gamedata.js, source/public/games.php, source/server/controller/DBManager.php, source/server/model/ships/EA/auroraStarfury.php, source/server/model/ships/EA/badgerStarfury.php, source/server/model/ships/EA/gammaStarfury.php, source/server/model/ships/EA/novaStarfury.php, source/server/model/ships/EA/thunderboltStarfury.php, source/server/model/ships/EA/thunderboltStarfuryNav.php, source/server/model/ships/EA/tigerStarfury.php, source/server/model/ships/abbai/aldrith.php, source/server/model/ships/brakiri/falkosi.php, source/server/model/ships/brakiri/folshotB.php, source/server/model/ships/brakiri/pikitos.php, source/server/model/ships/deneth/defenderFtr.php, source/server/model/ships/dilgar/koratyl.php, source/server/model/ships/drakh/drakhRaiderFlt.php, source/server/model/ships/raiders/deltaV.php, source/server/model/ships/raiders/deltaVAlt.php, source/server/model/ships/raiders/doubleV.php, source/server/model/ships/raiders/doubleV_nav.php, source/server/model/ships/starwars_centauri/zzftrAWing.php, source/server/model/ships/starwars_centauri/zzftrXWing.php, source/server/model/ships/starwars_centauri/zzftrYWing.php
=> Marcin fixes5

source/autoload.php, source/public/games.php, source/server/model/cricialClasses.php, source/server/model/ships/streib/adjudicator.php, source/server/model/ships/streib/collector.php, source/server/model/ships/streib/mothership.php, source/server/model/ships/streib/streibIntruder.php, source/server/model/ships/streib/streibMonitor.php, source/server/model/systems/baseSystems.php, source/server/model/weapons/specialWeapons.php
Streib fix
GravThrusters modified
=> Wolfgang ships2

source/public/client/power.js, source/server/handlers/firing.php, source/server/model/ships/customs/technicalTargetDrone.php
=> Marcin power fix

db/emptyDatabase.sql, source/autoload.php, source/public/client/UI/confirm.js, source/public/client/UI/flightwindow.js, source/public/client/UI/reactJs/UI.bundle.js, source/public/client/UI/reactJs/system/ShipInfo.js, source/public/client/UI/reactJs/system/SystemInfo.js, source/public/client/UI/shipwindow.js, source/public/client/ajaxInterface.js, source/public/client/gamelobby.js, source/server/Phase/BuyingGamePhase.php, source/server/controller/DBManager.php, source/server/controller/Manager.php, source/server/controller/shipLoader.php, source/server/handlers/EW.php, source/server/model/ships/EA/thunderboltStarfury.php, source/server/model/ships/EA/thunderboltStarfuryNav.php, source/server/model/ships/Enhancements.php, source/server/model/ships/ShipClasses.php, source/server/model/ships/centauri_old/phalanM.php, source/server/model/ships/centauri_old/phalanMNav.php, source/server/model/ships/narn/tarza.php, source/server/model/ships/narn/tarzanav.php, source/server/model/ships/raiders/doubleV.php, source/server/model/ships/raiders/doubleV_nav.php, source/server/model/systems/ShipSystem.php
=> Marcin enhancements

source/autoload.php, source/public/client/model/weapon/particle.js, source/server/model/ships/usuuth/baroon.php, source/server/model/ships/usuuth/orthuul.php, source/server/model/ships/usuuth/orthuus.php, source/server/model/ships/usuuth/rowlon.php, source/server/model/ships/usuuth/sarlon.php, source/server/model/ships/usuuth/serron.php, source/server/model/ships/usuuth/sethrus.php, source/server/model/ships/usuuth/sinthon.php, source/server/model/ships/usuuth/staroon.php, source/server/model/ships/usuuth/thira.php, source/server/model/systems/baseSystems.php, source/server/model/weapons/particle.php
Added three new weapons to support Usuuth
Marcin, I've added three new weapons (no images yet, I'll come up with some shortly).  I've added these to autoload, is there anywhere else that I need to make changes to for these weapons or should this be good?
=> New Weapons

source/server/model/ships/cascor/caccar.php, source/server/model/ships/cascor/calaq.php, source/server/model/ships/cascor/caltus.php, source/server/model/ships/cascor/coqari.php, source/server/model/ships/cascor/nesacc.php, source/server/model/ships/cascor/norsca.php, source/server/model/ships/cascor/qoccata.php, source/server/model/ships/cascor/tiqincc.php, source/server/model/ships/cascor/traqintor.php, source/server/model/ships/centauri/marcanos.php, source/server/model/ships/deneth/liberatorCannon.php, source/server/model/ships/deneth/liberatorEscort.php, source/server/model/ships/deneth/liberatorPlasma.php, source/server/model/ships/deneth/liberatorPulse.php, source/server/model/ships/smallraces/baLightGunboat.php, source/server/model/ships/smallraces/baLightGunboatEscort.php, source/server/model/ships/smallraces/baLightGunboatPulse.php, source/server/model/ships/smallraces/sorithiansyluscutter.php, source/server/model/ships/usuuth/baroon.php, source/server/model/ships/usuuth/staroon.php, source/server/model/ships/usuuth/thira.php, source/server/model/weapons/specialWeapons.php
=> first Cascor fixes

source/server/model/ships/drazi_old/auk.php, source/server/model/ships/drazi_old/earlywarbird.php, source/server/model/ships/drazi_old/earlywartalon.php, source/server/model/ships/drazi_old/egret.php, source/server/model/ships/drazi_old/heron.php, source/server/model/ships/drazi_old/merlin.php, source/server/model/ships/drazi_old/shrike.php, source/server/model/ships/drazi_old/skua.php, source/server/model/ships/drazi_old/swallow.php, source/server/model/ships/drazi_old/swift.php
Added hitcharts for Drazi (WotCR) vessels which didn't have any e.g. HCVs and Mediums.
=> Drazihitcharts

source/public/client/gamelobby.js
Better matching for special fighters requiring special hangars. Updated for future-proofing and better checking.
=> Special fighter hangar requirements

source/autoload.php, source/public/client/model/weapon/aoe.js, source/public/client/model/weapon/customNexus.js, source/server/Phase/MovementGamePhase.php, source/server/controller/DBManager.php, source/server/handlers/firing.php, source/server/model/ships/ShipClasses.php, source/server/model/ships/ZEscalationCircasian/CircasianXandar.php, source/server/model/ships/abbai_old/nota.php, source/server/model/ships/abbai_old/seta.php, source/server/model/ships/centauri/dargan.php, source/server/model/ships/customs/technicalTestbed.php, source/server/model/weapons/AoE.php, source/server/model/weapons/customNexus.php, source/server/model/weapons/specialWeapons.php, source/server/model/weapons/weapon.php
including activation related bugs (game highlighting, persistnet "unit already moved" )
=> lots of bug fixes

source/public/client/renderer/icon/BallisticIconContainer.js
=> Fix for Ballistic line error

source/autoload.php, source/server/model/ships/whatif/Dargarian_WI.php, source/server/model/ships/whatif/Mograte_WI.php
Added two additional "What If" Centauri
- Dargarian
- Mograte
=> Stano updates starting 30 September 25
